### ISSUE TITLE
Include `Anima::Update` per default.

### ISSUE THREAD

**Issue by mbj** [mbj/anima#13]
A recent analysis shows my personal usage of `Anima` is paired in `95%` of the cases with an inclusion of `Anima::Update` into the same host.

I do not think the optional `Anima::Update` has any justification than.

Interested in other peoples experience. //cc @snusnu, @plexus, @solnic, @dkubb.

**Comment by snusnu** [comment]
i agree with @plexus and think that `#with` would be a better name than `#update`. it makes it very obvious that a (new) object *with* the declared properties will be returned.

* `#update` implies mutation of the object
* calling a method `#copy` and then making it accept parameters seems a little weird to me. i'd expect `#copy` to return, well, a **copy**, i.e. nothing different from the original
* `#new` imo communicates less intent than `#with`
