### ISSUE TITLE
Add Anima.attribute_names

### ISSUE THREAD

**Issue by snusnu** [mbj/anima#15]
Recently, I've found myself doing `private(*anima.attributes.map(&:name))` quite often. Usually from within anima infected builder objects.

**Comment by snusnu** [comment]
lol https://github.com/mbj/anima/blob/master/lib/anima.rb#L77 closing ...

**Comment by mbj** [comment]
Seems like it has been there since 2012!

**Comment by snusnu** [comment]
haha
