### ISSUE TITLE
Optional attributes

### ISSUE THREAD

**Issue by martinciu** [mbj/anima#20]
What do you think about support for optional (with defaults) attributes?

Something like:

```ruby
class Person
  include Anima.new(:salutation, :firstname, :lastname, age: 18)
end

person = Person.new(salutation: 'Mr', firstname: 'James')
person.lastname # nil
person.age      # 18
```

**Comment by mbj** [comment]
No. Could be handled via an additional library. I do not want to clutter anima with features. The smaller the lib is the better it fits everywhere.

Yes its a drastic opinion. And but I gave an argument. If you have a good argument you'll be able to change my opinion.

There exist multiple attempts to create an "anima with defaults" frontend already. I support those in their existance. The best attempt is IMO that one: https://github.com/plexus/attribs //cc @plexus.

**Comment by mbj** [comment]
BTW: Anima is ment as a backend for object systems. Another way to use it is transproc + anima, something solnic did. 

This makes it clear why such a defaults feature does not make sense for anima itself. Because each use case needs different defaults semantics. AFAIK transproc also support default lambdas.

**Comment by martinciu** [comment]
I agree. Thanks for the tip about https://github.com/plexus/attribs.

Regarding transproc + anima, could you elaborate a little how could it work for optional or default attributes. 

Thanks!

**Comment by mbj** [comment]
> Regarding transproc + anima, could you elaborate a little how could it work for optional or default attributes.

Just ask @solnic about it. I'm not to firm its part of the ROM stack.

**Comment by mbj** [comment]
@martinciu Another thing, I flagged some issies with `attribs` once in a review. My guess is that @plexus would love to accept a PR that fixes them: https://github.com/plexus/attribs/commit/b4963e5b6c5236e041b95e0e445392d70160147a
