### ISSUE TITLE
Default values in initializer

### ISSUE THREAD

**Issue by mauricioszabo** [mbj/anima#29]
I think it would be a good practice to allow default values to attributes. Something like:

```ruby
require 'anima'

# Definition
class Person
  include Anima.new(name: '', age: 0)
end

a = Person.new(age: 30)
# => #<Person name="" age=30>
```

**Comment by mbj** [comment]
This was discussed multiple times and its not in the scope of this project. You can easily add default values on top in case:

```ruby
class Person
  include Anima.new(:name, :age)

  DEFAULTS = { name: '', age: 0 }

  def self.new(**attributes)
     super(DEFAULTS.merge(attributes))
  end
end
```

Defaults are in fact a form of conditionals and they should be used sparsely. I'll close this issue for now, but please keep trying to convince me with new arguments. I'm known to change my opinion on good ones.

Also in case you wanted you could easily create an `anima-defaults` gem adding the functionality, I'd be willing to link to it from the Readme assumig I see some use / maintainership of it.

**Comment by mauricioszabo** [comment]
I think it would mostly be because it's kinda easy to make the change. Also, this would allow this project to implement a kind of Null Object pattern, and ease the builder pattern too. That way, creating an "empty, default object" would be simply `MyObject.new`, and not 

`MyObject.new(attr: [], other_attr: "", something_else: SomethingElse.new(other => default, parameters => here))`

I think generating a new gem for it would be kinda overkill too...

**Comment by mbj** [comment]
so why not share your domain specific null object this way:

```
class YourClass
  include Anima.new(...)
  NULL = new(your_null_params)
end
```

this is superior to create n null objects. plus points for (deep) freezing it.
